server {
    listen 80;
    listen [::]:80;
    server_name 152-42-233-242.sslip.io;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        return 302 https://$host:8443$request_uri;
    }
}
